Fix some Python3 compatibility issues
1.TypeError: a bytes-like object is required, not 'str'

 Python3.X need use decode() to  change  "bytes" -> "str"

ft1.2: freezer_tempest_plugin.tests.freezerclient.test_freezer_cmd_action.TestFreezerCmdAction.test_freezer_cmd_actiondelete[gate]testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/opt/stack/tempest/.tox/tempest/lib/python3.6/site-packages/freezer_tempest_plugin/tests/freezerclient/test_freezer_cmd_action.py", line 79, in test_freezer_cmd_actiondelete
    action_id = err.split(' ')[1]
TypeError: a bytes-like object is required, not 'str'

2.AttributeError: module 'urllib' has no attribute 'urlencode'
ft1.2: freezer_tempest_plugin.tests.freezer_api.api.test_api_actions.TestFreezerApiActions.test_api_actions_get_limit[gate]testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/opt/stack/tempest/.tox/tempest/lib/python3.6/site-packages/freezer_tempest_plugin/tests/freezer_api/api/test_api_actions.py", line 46, in test_api_actions_get_limit
    resp, body = self.freezer_api_client.get_actions(limit=valid_limit)
  File "/opt/stack/tempest/.tox/tempest/lib/python3.6/site-packages/freezer_tempest_plugin/services/freezer_api_client.py", line 136, in get_actions
    uri += '?%s' % urllib.urlencode(params)
AttributeError: module 'urllib' has no attribute 'urlencode'

Change-Id: Ice774245605fe3549c7dacb9a2891d8177777f66